on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create local changes
        run: |
          ping -c 1 yusuke.cloud
          mkdir -p ./docs
          bash ./tinystatus > ./docs/index.html
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: publish
